#!/usr/bin/env tsx
// Phase 23: regenerates packages/core/src/data/char-shapes.generated.ts — radical, stroke counts
// and phonetic-component groups for every character in the lexicon, used by core/confusables to
// find look-alike characters. Source: the Unicode Unihan database (Unicode terms of use, see the
// Credits page): kRSUnicode and kTotalStrokes from Unihan_IRGSources.txt, kPhonetic from
// Unihan_DictionaryLikeData.txt (both in data/raw/, git-ignored; see data/raw/SOURCES.md).
// No decomposition data is used (the common IDS sets are GPL or unclear).
// Run via `pnpm --filter @anan/data-pipeline gen:char-shapes`.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '../../..');
const RAW = path.join(REPO_ROOT, 'data/raw');
const LEXICON = path.join(REPO_ROOT, 'data/build/lexicon.v2.json');
const OUT = path.join(REPO_ROOT, 'packages/core/src/data/char-shapes.generated.ts');

/** U+XXXX → { property → value } for the properties asked for. */
export function readUnihan(file: string, props: ReadonlySet<string>): Map<string, Map<string, string>> {
  const out = new Map<string, Map<string, string>>();
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    if (!line || line.startsWith('#')) continue;
    const [cp, prop, value] = line.split('\t');
    if (!cp || !prop || value === undefined || !props.has(prop)) continue;
    const ch = String.fromCodePoint(parseInt(cp.slice(2), 16));
    const m = out.get(ch) ?? new Map<string, string>();
    m.set(prop, value.trim());
    out.set(ch, m);
  }
  return out;
}

/** "154.5" → radical 154, 5 extra strokes ("120'.3": a simplified radical form, same number). */
export function parseRs(rs: string): [number, number] | undefined {
  const m = /^(\d+)'*\.(-?\d+)/.exec(rs.split(' ')[0] ?? '');
  return m ? [Number(m[1]), Number(m[2])] : undefined;
}

function main(): void {
  const irg = path.join(RAW, 'Unihan_IRGSources.txt');
  const dict = path.join(RAW, 'Unihan_DictionaryLikeData.txt');
  if (!existsSync(irg) || !existsSync(dict)) {
    console.error('gen-char-shapes: Unihan_IRGSources.txt / Unihan_DictionaryLikeData.txt missing from data/raw (see SOURCES.md).');
    process.exit(1);
  }
  const shapes = readUnihan(irg, new Set(['kRSUnicode', 'kTotalStrokes']));
  const phon = readUnihan(dict, new Set(['kPhonetic']));
  const lexicon = JSON.parse(readFileSync(LEXICON, 'utf8')) as { charIndex: Record<string, unknown> };
  const chars = Object.keys(lexicon.charIndex)
    .filter((c) => /\p{Script=Han}/u.test(c))
    .sort();
  const lines: string[] = [];
  let missing = 0;
  for (const ch of chars) {
    const rs = parseRs(shapes.get(ch)?.get('kRSUnicode') ?? '');
    // Two stroke counts: the first is for zh-Hans, the last for zh-Hant (UAX #38): Taiwan uses the last.
    const strokes = Number((shapes.get(ch)?.get('kTotalStrokes') ?? '').split(' ').pop());
    if (!rs || !Number.isFinite(strokes)) {
      missing++;
      continue;
    }
    // kPhonetic values look like "864 1083" or "1648B*": keep the group numbers only.
    const groups = (phon.get(ch)?.get('kPhonetic') ?? '')
      .split(' ')
      .map((g) => /^\d+/.exec(g)?.[0])
      .filter((g): g is string => !!g);
    lines.push(`  ${JSON.stringify(ch)}: ${JSON.stringify(`${rs[0]}.${rs[1]}|${strokes}|${[...new Set(groups)].join(' ')}`)},`);
  }
  const out = `// GENERATED by packages/data-pipeline/src/gen-char-shapes.ts from the Unicode Unihan database
// (kRSUnicode, kTotalStrokes, kPhonetic; Unicode terms of use) — do not hand-edit.
// One entry per character in the lexicon: "radical.extraStrokes|totalStrokes|phonetic groups".
export const CHAR_SHAPES: Record<string, string> = {
${lines.join('\n')}
};
`;
  writeFileSync(OUT, out, 'utf8');
  console.log(`gen-char-shapes: ${lines.length} characters (${missing} without Unihan data) -> ${path.relative(REPO_ROOT, OUT)}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) main();
