#!/usr/bin/env tsx
// Regenerates packages/core/src/data/{mainland-terms,simplified-chars}.generated.ts
// from the hand-curated YAML in data/supplement/. Run via `pnpm --filter
// @anan/data-pipeline gen:taiwanness` (also invoked by build-lexicon.ts).
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadMainlandTermsYaml, loadSimplifiedCharsYaml } from './lib/supplement.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '../../..');
const DATA_SUPPLEMENT = path.join(REPO_ROOT, 'data/supplement');
const CORE_DATA = path.join(REPO_ROOT, 'packages/core/src/data');

function tsStringLiteral(s: string): string {
  return JSON.stringify(s);
}

function genMainlandTerms(): void {
  const entries = loadMainlandTermsYaml(path.join(DATA_SUPPLEMENT, 'mainland-terms.yaml'));
  const lines = entries.map((e) => {
    const mainland = `[${e.mainland.map(tsStringLiteral).join(', ')}]`;
    const note = e.note ? `, note: ${tsStringLiteral(e.note)}` : '';
    return `  { mainland: ${mainland}, taiwan: ${tsStringLiteral(e.taiwan)}${note} },`;
  });
  const out = `// GENERATED by packages/data-pipeline/src/gen-taiwanness-data.ts from
// data/supplement/mainland-terms.yaml — do not hand-edit; edit the YAML and
// re-run \`pnpm pipeline:build\` (or \`pnpm --filter @anan/data-pipeline gen:taiwanness\`) instead.
export interface MainlandTermEntry {
  mainland: string[];
  taiwan: string;
  note?: string;
}

export const MAINLAND_TERMS: MainlandTermEntry[] = [
${lines.join('\n')}
];
`;
  writeFileSync(path.join(CORE_DATA, 'mainland-terms.generated.ts'), out, 'utf8');
}

function genSimplifiedChars(): void {
  const pairs = loadSimplifiedCharsYaml(path.join(DATA_SUPPLEMENT, 'simplified-only-chars.yaml'));
  const lines = pairs.map((p) => `  ${tsStringLiteral(p.simplified)}: ${tsStringLiteral(p.traditional)},`);
  const out = `// GENERATED by packages/data-pipeline/src/gen-taiwanness-data.ts from
// data/supplement/simplified-only-chars.yaml — do not hand-edit; edit the
// YAML and re-run \`pnpm pipeline:build\` instead.
//
// Hand-curated table of characters used ONLY in Simplified Chinese (the
// traditional form is a different character/shape). Deliberately excludes
// characters that are shared or ambiguous between scripts even though a
// simplification mapping exists elsewhere — e.g. 台 (also standard
// traditional usage in 台灣), 后 (also traditional "empress/queen"), 云
// (also classical traditional "to say") — including those would
// false-positive on legitimate Taiwan text. See CLAUDE.md "Open items to
// verify, not assume": this is a partial, conservatively-curated list, not
// a Unihan/OpenCC-derived table.
export const SIMPLIFIED_ONLY_CHARS: Record<string, string> = {
${lines.join('\n')}
};
`;
  writeFileSync(path.join(CORE_DATA, 'simplified-chars.generated.ts'), out, 'utf8');
}

genMainlandTerms();
genSimplifiedChars();
console.log('Regenerated packages/core/src/data/{mainland-terms,simplified-chars}.generated.ts');
