export interface ImportStats {
  lessons: Array<{
    n: number;
    titleEn: string;
    counts: { core: number; phrase: number; proper: number; supplementary: number };
    grammar: number;
    examples: number;
    dialogueLines: number;
  }>;
  totalEntries: number;
  uniqueWords?: number;
  statedWords: number;
  statedGrammar: number;
  grammarCount: number;
  cleanups: string[];
  unlinked: string[];
  weakLinks: string[];
  indexMissing: string[];
  duplicates: string[];
  manual: string[];
  dialogueNotes: string[];
  /** Phase 13 (per-book importer): which book this report is for. */
  bookId?: string;
  titleZh?: string;
  /** PDF pages of the appendix vocabulary index (for the headings below). */
  indexPages?: [number, number];
  /** Index entries whose headword differs from the lesson entry at the same `lesson-n` locator. */
  locatorMismatches?: string[];
  /** Number of index entries / entries confirmed at their locator. */
  locatorChecked?: { entries: number; confirmed: number };
  /** Numbered entries that are sentence patterns with …… (grammar, not lexicon items). */
  patternEntries?: string[];
  /** Why the parsed counts may differ from the book's stated counts (from config.json). */
  explanations?: string[];
  /** Entries whose word an earlier book already taught (one item, tagged by both books). */
  reintroduced?: string[];
}

const list = (xs: string[]) => (xs.length ? xs.map((x) => `- ${x}`).join('\n') : '- none');

export function buildReport(s: ImportStats): string {
  const rows = s.lessons
    .map(
      (l) =>
        `| ${l.n} | ${l.titleEn} | ${l.counts.core} | ${l.counts.phrase} | ${l.counts.proper} | ${l.counts.supplementary} | ${l.grammar} | ${l.dialogueLines} | ${l.examples} |`,
    )
    .join('\n');
  const diff = s.totalEntries - s.statedWords;
  const title = s.titleZh ?? '來學華語 第一冊';
  const bookId = s.bookId ?? 'laixue-1';
  const [ia, ib] = s.indexPages ?? [174, 182];
  const locator = s.locatorChecked
    ? `\n## Cross-check against the appendix index (locators)
The index lists every word with its \`lesson-n\` position. **${s.locatorChecked.confirmed}** of **${s.locatorChecked.entries}** index entries sit at a parsed lesson entry with the same headword (or a listed variant).
${list(s.locatorMismatches ?? [])}
`
    : '';
  const reintro = s.reintroduced
    ? `\n## Words an earlier book already taught
These entries link to the SAME lexicon item as the earlier lesson, which keeps one item tagged with every lesson that teaches it (${s.reintroduced.length} in this book).
${list(s.reintroduced)}
`
    : '';
  const patterns = s.patternEntries
    ? `\n## Sentence-pattern entries (…… in the headword; counted in the book, kept out of the lexicon)
${list(s.patternEntries)}
`
    : '';
  const explain = s.explanations?.length
    ? `\n## Differences from the book's stated numbers, explained
${list(s.explanations)}
`
    : '';
  return `# Import report — ${title}

Generated by \`pnpm curriculum:import ${bookId}\`. Book text itself is not in this report.

## Counts vs the book

| L | Title | 生詞 | 短語 | 專有名詞 | 補充 | Grammar | Dialogue lines | Examples |
|---|-------|------|------|----------|------|---------|----------------|----------|
${rows}

- Numbered vocabulary entries parsed: **${s.totalEntries}** (the book states **${s.statedWords}** new words). Difference: ${diff >= 0 ? '+' : ''}${diff}.
- Distinct word+sense entries (a repeat of the same word and sense counted once): **${s.uniqueWords ?? '?'}** — ${s.uniqueWords === s.statedWords ? 'matches the book' : 'differs from the book'}. Repeats are listed below.
- Grammar points: **${s.grammarCount}** (the book states **${s.statedGrammar}**) — ${s.grammarCount === s.statedGrammar ? 'match' : 'MISMATCH'}.

### Words that recur across lessons
${list(s.duplicates)}
${explain}${reintro}${patterns}${locator}
## Cleanups applied to extracted headwords (ruby duplicates, variants, punctuation)
${list(s.cleanups)}

## Not found in the appendix vocabulary index (PDF p${ia}–${ib})
The index is itself missing some entries and glues others, so this is a hint, not an error list.
${list(s.indexMissing)}

## Words with no lexicon match (created as textbook entries, level N1)
${list(s.unlinked)}

## Weak lexicon links (readings differ by tone/sandhi or gloss overlap is low) — review
${list(s.weakLinks)}

## Manual transcriptions and decisions
${list(s.manual)}

## Dialogue extraction notes
${list(s.dialogueNotes)}
`;
}
