export interface ImportStats {
  lessons: Array<{
    n: number;
    titleEn: string;
    counts: { core: number; phrase: number; proper: number; supplementary: number };
    grammar: number;
    examples: number;
    dialogueLines: number;
  }>;
  totalEntries: number;
  uniqueWords?: number;
  statedWords: number;
  statedGrammar: number;
  grammarCount: number;
  cleanups: string[];
  unlinked: string[];
  weakLinks: string[];
  indexMissing: string[];
  duplicates: string[];
  manual: string[];
  dialogueNotes: string[];
}

const list = (xs: string[]) => (xs.length ? xs.map((x) => `- ${x}`).join('\n') : '- none');

export function buildReport(s: ImportStats): string {
  const rows = s.lessons
    .map(
      (l) =>
        `| ${l.n} | ${l.titleEn} | ${l.counts.core} | ${l.counts.phrase} | ${l.counts.proper} | ${l.counts.supplementary} | ${l.grammar} | ${l.dialogueLines} | ${l.examples} |`,
    )
    .join('\n');
  const diff = s.totalEntries - s.statedWords;
  return `# Import report — 來學華語 第一冊

Generated by \`pnpm curriculum:import laixue-1\`. Book text itself is not in this report.

## Counts vs the book

| L | Title | 生詞 | 短語 | 專有名詞 | 補充 | Grammar | Dialogue lines | Examples |
|---|-------|------|------|----------|------|---------|----------------|----------|
${rows}

- Numbered vocabulary entries parsed: **${s.totalEntries}** (the book states **${s.statedWords}** new words). Difference: ${diff >= 0 ? '+' : ''}${diff}.
- Distinct word+sense entries (a repeat of the same word and sense counted once): **${s.uniqueWords ?? '?'}** — ${s.uniqueWords === s.statedWords ? 'matches the book' : 'differs from the book'}. Repeats are listed below.
- Grammar points: **${s.grammarCount}** (the book states **${s.statedGrammar}**) — ${s.grammarCount === s.statedGrammar ? 'match' : 'MISMATCH'}.

### Words that recur across lessons
${list(s.duplicates)}

## Cleanups applied to extracted headwords (ruby duplicates, variants, punctuation)
${list(s.cleanups)}

## Not found in the appendix vocabulary index (PDF p174+)
The index is itself missing some entries and glues others, so this is a hint, not an error list.
${list(s.indexMissing)}

## Words with no lexicon match (created as textbook entries, level N1)
${list(s.unlinked)}

## Weak lexicon links (readings differ by tone/sandhi or gloss overlap is low) — review
${list(s.weakLinks)}

## Manual transcriptions and decisions
${list(s.manual)}

## Dialogue extraction notes
${list(s.dialogueNotes)}
`;
}
