// GENERATED by packages/data-pipeline/src/gen-taiwanness-data.ts from
// data/supplement/mainland-terms.yaml — do not hand-edit; edit the YAML and
// re-run `pnpm pipeline:build` (or `pnpm --filter @anan/data-pipeline gen:taiwanness`) instead.
export interface MainlandTermEntry {
  mainland: string[];
  taiwan: string;
  note?: string;
}

export const MAINLAND_TERMS: MainlandTermEntry[] = [
  { mainland: ["地铁", "地鐵"], taiwan: "捷運", note: "Taipei/Kaohsiung metro; 地鐵 is not used in Taiwan signage." },
  { mainland: ["摩托车", "摩托車"], taiwan: "機車", note: "機車 is the everyday Taiwan word for a scooter/motorbike." },
  { mainland: ["出租车", "出租車"], taiwan: "計程車" },
  { mainland: ["软件"], taiwan: "軟體" },
  { mainland: ["视频"], taiwan: "影片", note: "Mainland 视频 = video; Taiwan uses 影片. (視訊 exists in Taiwan too, for video-call/streaming contexts.)" },
  { mainland: ["信息"], taiwan: "資訊", note: "信息 is understood in Taiwan but reads as mainland-flavored; 資訊 is the Taiwan default for 'information'." },
  { mainland: ["质量", "質量"], taiwan: "品質", note: "Contextual: mainland 质量 covers both 'quality' and physics 'mass'; Taiwan uses 品質 for quality and 質量 only for mass. Flag, don't auto-replace, when used in a physics context." },
  { mainland: ["公交车", "公交車"], taiwan: "公車" },
  { mainland: ["自行车", "自行車"], taiwan: "腳踏車", note: "單車 is also fine in Taiwan; 腳踏車 is the more traditional/common term." },
  { mainland: ["土豆"], taiwan: "馬鈴薯", note: "Mainland 土豆 = potato; in Taiwan 土豆 means peanut (花生 elsewhere on the mainland)." },
  { mainland: ["洋葱", "洋蔥"], taiwan: "洋蔥", note: "Same word; 洋葱 is the simplified spelling flag only, no vocabulary difference." },
  { mainland: ["优盘", "隨身碟"], taiwan: "隨身碟" },
  { mainland: ["打车"], taiwan: "叫計程車" },
  { mainland: ["视频通话", "視頻通話"], taiwan: "視訊通話" },
  { mainland: ["快递", "快遞"], taiwan: "宅配", note: "快遞 is understood in Taiwan for courier/express mail; 宅配 is the common home-delivery term. Flag rather than hard-replace." },
];
